const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(__dirname+'/index.html','utf8');const base=html.match(/<script>([\s\S]*?)<\/script>/)[1],extension=fs.readFileSync(__dirname+'/order-workspace.js','utf8');
function runtime(){const nodes=new Map(),local=new Map();const node=id=>{if(!nodes.has(id))nodes.set(id,{innerHTML:'',value:'',textContent:'',classList:{toggle(){},add(){},remove(){}},insertAdjacentHTML(_,s){this.innerHTML+=s},querySelector(){return null}});return nodes.get(id)};const ctx=vm.createContext({console,structuredClone,Intl,Date,Math,crypto:require('node:crypto').webcrypto,URL,Blob,localStorage:{getItem:k=>local.get(k)||null,setItem:(k,v)=>local.set(k,v)},window:{addEventListener(){},scrollTo(){},print(){}},document:{getElementById:node,querySelectorAll(){return[]},documentElement:{lang:'en'}},setTimeout(){},confirm(){return true}});vm.runInContext(base,ctx);vm.runInContext(extension,ctx);const run=s=>vm.runInContext(s,ctx);run('renderAll=renderOrders=renderPortal=renderAdmin=renderHeader=renderSummary=renderQuick=renderCollection=()=>{};toast=()=>{};go=p=>{state.page=p}');return run}
let n=0;function test(name,fn){const r=runtime();fn(r);n++;console.log('PASS '+name)}
function seed(r){r("state.draft={p1:{Stone:{'50':2}}};state.draftMeta={client:owClient().name,delivery:'2026-12-01',notes:''}");return r("owMakeOrder('submitted').id")}
test('migration removes retail sell-through state and separates client types',r=>{assert.equal(r('state.salesOS'),undefined);assert.equal(r('state.sellThrough'),undefined);assert.equal(r('owClient().kind'),'company');r("owActivate('c-private',false)");assert.equal(r('owClient().kind'),'person');assert.equal(r('state.role'),'private')});
test('client price and discount precedence, cent accuracy',r=>{assert.equal(r('owPrice(state.products[0])'),257.6);assert.equal(r("owPrice(state.products[0],'c-paris')"),250);r("owClient().prices.p1={discount:10}");assert.equal(r('owPrice(state.products[0])'),252);r("owClient().prices.p1={price:249.99}");assert.equal(r('owPrice(state.products[0])'),249.99)});
test('company/private base prices differ',r=>{assert.equal(r("owPrice(state.products[0],'c-private')"),590);assert.equal(r("owPrice(state.products[0],'c-milano')"),257.6)});
test('client switch isolates drafts and wishlists',r=>{r("state.draft={p1:{Stone:{'50':3}}};state.orderDesk.wishlists['c-milano']=['p1'];owActivate('c-paris');state.draft={p2:{Black:{'50':1}}};owActivate('c-milano')");assert.equal(r("state.draft.p1.Stone['50']"),3);assert.equal(r('state.draft.p2'),undefined);assert.equal(r("isFav('p1')"),true)});
test('inactive product cannot be submitted',r=>{r("state.draft={p1:{Stone:{'50':2}}};state.products[0].active=false");const before=r('state.orders.length');assert.equal(r("owMakeOrder('submitted')"),null);assert.equal(r('state.orders.length'),before)});
test('fractional and unsupported variants cannot be submitted',r=>{r("state.draft={p1:{Stone:{'50':1.5}}}");assert.equal(r("owMakeOrder('submitted')"),null);r("state.draft={p1:{Unsupported:{'50':2}}}");assert.equal(r("owMakeOrder('submitted')"),null)});
test('draft save then submit creates one order',r=>{r("state.draft={p1:{Stone:{'50':2}}}");const before=r('state.orders.length');r("owMakeOrder('draft');owMakeOrder('submitted')");assert.equal(r('state.orders.length'),before+1);assert.equal(r('state.orders[0].status'),'submitted')});
test('bilateral finalization requires manager then owning client',r=>{seed(r);assert.equal(r('owOffer(state.selectedOrder)'),false);r("state.role='brand'");assert.equal(r('owOffer(state.selectedOrder)'),true);assert.equal(r('owConfirmed(state.orders[0])'),false);r("state.role='buyer';state.orderDesk.activeClientId='c-paris'");assert.equal(r('owAccept(state.selectedOrder)'),false);r("state.orderDesk.activeClientId='c-milano'");assert.equal(r('owAccept(state.selectedOrder)'),true);assert.equal(r('owAccept(state.selectedOrder)'),false);assert.equal(r('owConfirmed(state.orders[0])'),true)});
test('catalog/client edits do not mutate submitted order snapshots',r=>{seed(r);const price=r('state.orders[0].lines[0].unit'),article=r('state.orders[0].lines[0].article'),city=r('state.orders[0].clientSnapshot.city');r("state.products[0].b2b=999;state.products[0].article='CHANGED';owClient().city='CHANGED'");assert.equal(r('state.orders[0].lines[0].unit'),price);assert.equal(r('state.orders[0].lines[0].article'),article);assert.equal(r('state.orders[0].clientSnapshot.city'),city)});
test('revision stores old terms and removes both confirmations',r=>{seed(r);r("state.role='brand';owOffer(state.selectedOrder);state.role='buyer';owAccept(state.selectedOrder);state.role='brand';owEditOrder(state.selectedOrder,{lines:state.orders[0].lines.map(l=>({...l,qty:4,unit:230})),discount:10,delivery:'2026-12-08',terms:'New',paymentTerms:'New',notes:'Revision'},'Quantity change')");assert.equal(r('state.orders[0].revision'),2);assert.equal(r('state.orders[0].revisions[0].lines[0].qty'),2);assert.equal(r('owConfirmed(state.orders[0])'),false);assert.equal(r('orderValue(state.orders[0])'),828)});
test('invalid revision cannot partly mutate order',r=>{seed(r);r("state.role='brand'");assert.throws(()=>r("owEditOrder(state.selectedOrder,{lines:[{qty:-1,unit:100}],discount:10},'bad')"));assert.equal(r('state.orders[0].revision'),1)});
test('season reporting allocates mixed-season orders without double count',r=>{seed(r);r("state.role='brand';owOffer(state.selectedOrder);state.role='buyer';owAccept(state.selectedOrder);state.orders[0].lines.push({...state.orders[0].lines[0],season:'SS 27',qty:1});state.orderDesk.filters.season='FW 26/27'");assert.equal(r("owEntries().filter(e=>e.o.id===state.orders[0].id).length"),1);assert.equal(r("owGroups(owEntries().filter(e=>e.o.id===state.orders[0].id))[0].orders"),1)});
test('only confirmed orders are included in confirmed value',r=>{seed(r);const before=r('owEntries().filter(e=>owConfirmed(e.o)).reduce((a,e)=>a+e.value,0)');r("state.role='brand';owOffer(state.selectedOrder)");assert.equal(r('owEntries().filter(e=>owConfirmed(e.o)).reduce((a,e)=>a+e.value,0)'),before);r("state.role='buyer';owAccept(state.selectedOrder)");assert.equal(r('owEntries().filter(e=>owConfirmed(e.o)).reduce((a,e)=>a+e.value,0)'),before+515.2)});
test('custom request needs brand quote and buyer acceptance',r=>{r("state.orderDesk.requests.push({id:'r1',clientId:'c-milano',productId:'p1',color:'Burgundy',composition:'100% silk · demo',size:'50',qty:3,status:'requested',history:[],at:new Date().toISOString()})");assert.equal(r("owAcceptRequest('r1')"),false);r("state.role='brand';owQuote('r1',315.5,'2026-12-05','Possible · demo')");assert.equal(r("owAcceptRequest('r1')"),false);r("state.role='buyer'");assert.equal(r("owAcceptRequest('r1')"),true);assert.equal(r("owDraftLines()[0].composition"),'100% silk · demo');assert.equal(r("owMakeOrder('submitted').lines[0].unit"),315.5);assert.equal(r("state.orderDesk.requests[0].orderId"),r('state.selectedOrder'))});
test('accepted request cannot be ordered twice',r=>{r("state.orderDesk.requests.push({id:'r1',clientId:'c-milano',productId:'p1',color:'Burgundy',size:'50',qty:1,unit:300,status:'offered',history:[]});owAcceptRequest('r1');const l=structuredClone(state.customDraft[0]);owMakeOrder('submitted');state.customDraft=[l]");assert.equal(r("owMakeOrder('submitted')"),null)});
test('set adds top and bottom but not mandatory quantities',r=>{assert.equal(r("owOrderSet('set-demo-01')"),true);assert.equal(r('owDraftLines().length'),2);assert.equal(r('owDraftLines().reduce((n,l)=>n+l.qty,0)'),2)});
test('unsafe media URLs and duplicate articles rejected',r=>{assert.throws(()=>r("owURL('javascript:alert(1)')"));assert.throws(()=>r("owURL(\"https://example.com/x'bad\")"));r("state.role='brand'");assert.throws(()=>r("owSaveProduct({...state.products[0],id:'NEW',photos:[]})"));assert.equal(r('state.products.length'),11)});
test('negative client discounts and conflicting price rules rejected',r=>{r("state.role='brand'");assert.throws(()=>r("owSaveClient({...owClient(),discount:-1})"));assert.throws(()=>r("owSaveClient({...owClient(),prices:{p1:{price:250,discount:10}}})"))});
test('CSV export is formula-safe and carries snapshots/terms',r=>{assert.equal(r("owCSVCell('=HYPERLINK(1)')"),'"\'=HYPERLINK(1)"');seed(r);assert.equal(r('owReportRows().some(row=>row.includes(257.6))'),true);assert.equal(r('owReportRows()[2].includes("Terms")'),true)});
test('private customer sees only their orders',r=>{seed(r);r("owActivate('c-private',false)");assert.equal(r("owVisibleOrders().some(o=>o.clientId==='c-milano')"),false);assert.equal(r("owVisibleOrders().every(o=>o.clientId==='c-private')"),true)});
test('catalog draft publication and media metadata stay intact',r=>{r("state.role='brand';owSaveProduct({...state.products[0],id:'new-product',article:'NEW-01',active:false,photos:['https://example.com/product.jpg'],videoUrl:'https://example.com/video.mp4'})");assert.equal(r("state.products.find(p=>p.id==='new-product').active"),false);assert.equal(r("state.products.find(p=>p.id==='new-product').videoUrl"),'https://example.com/video.mp4');r("owToggleProduct('new-product')");assert.equal(r("state.products.find(p=>p.id==='new-product').active"),true)});
console.log(n+' order workspace behavioral checks passed');
